//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChangeBlog.Api.Localization.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ChangeBlogStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ChangeBlogStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChangeBlog.Api.Localization.Resources.ChangeBlogStrings", typeof(ChangeBlogStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Account has been deleted.
        /// </summary>
        public static string AccountDeleted {
            get {
                return ResourceManager.GetString("AccountDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account not found.
        /// </summary>
        public static string AccountNotFound {
            get {
                return ResourceManager.GetString("AccountNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Api Key successfully added.
        /// </summary>
        public static string ApiKeyAdded {
            get {
                return ResourceManager.GetString("ApiKeyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Api Key successfully deleted.
        /// </summary>
        public static string ApiKeyDeleted {
            get {
                return ResourceManager.GetString("ApiKeyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The api key expiration is too long. Expiration must be smaller than 2 years.
        /// </summary>
        public static string ApiKeyExpirationTooLong {
            get {
                return ResourceManager.GetString("ApiKeyExpirationTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The api key expiration is too short. Expiration must be at least 1 week.
        /// </summary>
        public static string ApiKeyExpirationTooShort {
            get {
                return ResourceManager.GetString("ApiKeyExpirationTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changelog line successfully added.
        /// </summary>
        public static string ChangeLogLineAdded {
            get {
                return ResourceManager.GetString("ChangeLogLineAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested Changelog line has been deleted.
        /// </summary>
        public static string ChangeLogLineDeleted {
            get {
                return ResourceManager.GetString("ChangeLogLineDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while inserting or updating Changelog lines. Please try again later.
        /// </summary>
        public static string ChangeLogLineErrorOnInsertOrUpdate {
            get {
                return ResourceManager.GetString("ChangeLogLineErrorOnInsertOrUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The changelog line has been made pending.
        /// </summary>
        public static string ChangeLogLineMadePending {
            get {
                return ResourceManager.GetString("ChangeLogLineMadePending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changelog line(s) successfully moved.
        /// </summary>
        public static string ChangeLogLineMoved {
            get {
                return ResourceManager.GetString("ChangeLogLineMoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changelog line not found.
        /// </summary>
        public static string ChangeLogLineNotFound {
            get {
                return ResourceManager.GetString("ChangeLogLineNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changelog line is pending.
        /// </summary>
        public static string ChangeLogLinePending {
            get {
                return ResourceManager.GetString("ChangeLogLinePending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lines with same text are not allowed. Duplicate: &apos;{0}&apos;.
        /// </summary>
        public static string ChangeLogLineSameText {
            get {
                return ResourceManager.GetString("ChangeLogLineSameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} changelog lines has been made pending.
        /// </summary>
        public static string ChangeLogLinesMadePending {
            get {
                return ResourceManager.GetString("ChangeLogLinesMadePending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chnagelog line successfully updated.
        /// </summary>
        public static string ChangeLogLineUpdated {
            get {
                return ResourceManager.GetString("ChangeLogLineUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The changelog line is not pending.
        /// </summary>
        public static string ChnageLogLineNotPending {
            get {
                return ResourceManager.GetString("ChnageLogLineNotPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Api Key Title is invalid.
        /// </summary>
        public static string InvalidApiKeyTitle {
            get {
                return ResourceManager.GetString("InvalidApiKeyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid changelog text &apos;{0}&apos;.
        /// </summary>
        public static string InvalidChangeLogText {
            get {
                return ResourceManager.GetString("InvalidChangeLogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid format &apos;{0}&apos;.
        /// </summary>
        public static string InvalidFormat {
            get {
                return ResourceManager.GetString("InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid issue &apos;{0}&apos;.
        /// </summary>
        public static string InvalidIssue {
            get {
                return ResourceManager.GetString("InvalidIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid label &apos;{0}&apos;.
        /// </summary>
        public static string InvalidLabel {
            get {
                return ResourceManager.GetString("InvalidLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid name &apos;{0}&apos;.
        /// </summary>
        public static string InvalidName {
            get {
                return ResourceManager.GetString("InvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version &apos;{0}&apos; isn&apos;t properly formatted.
        /// </summary>
        public static string InvalidVersionFormat {
            get {
                return ResourceManager.GetString("InvalidVersionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid version id.
        /// </summary>
        public static string InvalidVersionId {
            get {
                return ResourceManager.GetString("InvalidVersionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid versioning scheme id.
        /// </summary>
        public static string InvalidVersioningSchemeId {
            get {
                return ResourceManager.GetString("InvalidVersioningSchemeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue successfully added.
        /// </summary>
        public static string IssueAdded {
            get {
                return ResourceManager.GetString("IssueAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue successfully deleted.
        /// </summary>
        public static string IssueDeleted {
            get {
                return ResourceManager.GetString("IssueDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label successfully added.
        /// </summary>
        public static string LabelAdded {
            get {
                return ResourceManager.GetString("LabelAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label successfully deleted.
        /// </summary>
        public static string LabelDeleted {
            get {
                return ResourceManager.GetString("LabelDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given language code &apos;{0}&apos; is not supported. Supported codes are &apos;{1}&apos;.
        /// </summary>
        public static string LanguageCodeNotSupported {
            get {
                return ResourceManager.GetString("LanguageCodeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t add more Issues. The max number of Issues is {0}.
        /// </summary>
        public static string MaxIssuesReached {
            get {
                return ResourceManager.GetString("MaxIssuesReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t add more Labels. The max number of Labels is {0}.
        /// </summary>
        public static string MaxLabelsReached {
            get {
                return ResourceManager.GetString("MaxLabelsReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing request data.
        /// </summary>
        public static string MissingRequestData {
            get {
                return ResourceManager.GetString("MissingRequestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;sub&apos; claim is missing in the access token.
        /// </summary>
        public static string MissingSubClaim {
            get {
                return ResourceManager.GetString("MissingSubClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no Chnagelog lines to assign.
        /// </summary>
        public static string NoChangeLogLinesToAssign {
            get {
                return ResourceManager.GetString("NoChangeLogLinesToAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permission to perform this operation.
        /// </summary>
        public static string NoPermissionToPerformThisOperation {
            get {
                return ResourceManager.GetString("NoPermissionToPerformThisOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authenticated. Please add a valid api key or access token.
        /// </summary>
        public static string NotAuthenticated {
            get {
                return ResourceManager.GetString("NotAuthenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Changelog line successfully added.
        /// </summary>
        public static string PendingChangeLogLineAdded {
            get {
                return ResourceManager.GetString("PendingChangeLogLineAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product successfully added.
        /// </summary>
        public static string ProductAdded {
            get {
                return ResourceManager.GetString("ProductAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product is already closed.
        /// </summary>
        public static string ProductAlreadyClosed {
            get {
                return ResourceManager.GetString("ProductAlreadyClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Product already exists.
        /// </summary>
        public static string ProductAlreadyExists {
            get {
                return ResourceManager.GetString("ProductAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The related product has been closed.
        /// </summary>
        public static string ProductHasBeenClosed {
            get {
                return ResourceManager.GetString("ProductHasBeenClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product not found.
        /// </summary>
        public static string ProductNotFound {
            get {
                return ResourceManager.GetString("ProductNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product does not contain any versions.
        /// </summary>
        public static string ProductWithoutVersions {
            get {
                return ResourceManager.GetString("ProductWithoutVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource not found.
        /// </summary>
        public static string ResourceNotFound {
            get {
                return ResourceManager.GetString("ResourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target version belongs to a different product.
        /// </summary>
        public static string TargetVersionBelongsToDifferentProduct {
            get {
                return ResourceManager.GetString("TargetVersionBelongsToDifferentProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target version has already lines with an identical text. Duplicates: &apos;{0}&apos;.
        /// </summary>
        public static string TargetVersionContainsLinesWithSameText {
            get {
                return ResourceManager.GetString("TargetVersionContainsLinesWithSameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target version has reached the max count of changelog lines. Max {0} lines possible.
        /// </summary>
        public static string TargetVersionTooManyChangeLogLines {
            get {
                return ResourceManager.GetString("TargetVersionTooManyChangeLogLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many Changelog lines. Max {0} lines.
        /// </summary>
        public static string TooManyChangeLogLines {
            get {
                return ResourceManager.GetString("TooManyChangeLogLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are too many Changelog lines to add. You can only add {0} more.
        /// </summary>
        public static string TooManyChangeLogLines_Remaining {
            get {
                return ResourceManager.GetString("TooManyChangeLogLines_Remaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The changelog line &apos;{0}&apos; has too many issues. Max {1} issues possible.
        /// </summary>
        public static string TooManyIssuesForChangeLogLine {
            get {
                return ResourceManager.GetString("TooManyIssuesForChangeLogLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The changelog line &apos;{0}&apos; has too many labels. Max {1} labels possible.
        /// </summary>
        public static string TooManyLabelsForChangeLogLine {
            get {
                return ResourceManager.GetString("TooManyLabelsForChangeLogLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Error.
        /// </summary>
        public static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User does not exist in the app.
        /// </summary>
        public static string UserNotExistingInApp {
            get {
                return ResourceManager.GetString("UserNotExistingInApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Profile successfully updated.
        /// </summary>
        public static string UserProfileUpdated {
            get {
                return ResourceManager.GetString("UserProfileUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version successfully added.
        /// </summary>
        public static string VersionAdded {
            get {
                return ResourceManager.GetString("VersionAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version has already been deleted.
        /// </summary>
        public static string VersionAlreadyDeleted {
            get {
                return ResourceManager.GetString("VersionAlreadyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version already exists.
        /// </summary>
        public static string VersionAlreadyExists {
            get {
                return ResourceManager.GetString("VersionAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The related version has already been released.
        /// </summary>
        public static string VersionAlreadyReleased {
            get {
                return ResourceManager.GetString("VersionAlreadyReleased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version cannot be deleted because it has already been released.
        /// </summary>
        public static string VersionCannotBeDeletedBecauseReleased {
            get {
                return ResourceManager.GetString("VersionCannotBeDeletedBecauseReleased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version cannot be released because it has already been deleted.
        /// </summary>
        public static string VersionCannotBeReleasedBecauseDeleted {
            get {
                return ResourceManager.GetString("VersionCannotBeReleasedBecauseDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The related version has been deleted.
        /// </summary>
        public static string VersionDeleted {
            get {
                return ResourceManager.GetString("VersionDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Version &apos;{0}&apos; does not match your product&apos;s versioning scheme. Versioningscheme: {1}.
        /// </summary>
        public static string VersioningSchemeMismatch {
            get {
                return ResourceManager.GetString("VersioningSchemeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versioningscheme not found.
        /// </summary>
        public static string VersioningSchemeNotFound {
            get {
                return ResourceManager.GetString("VersioningSchemeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version not found.
        /// </summary>
        public static string VersionNotFound {
            get {
                return ResourceManager.GetString("VersionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version successfully released.
        /// </summary>
        public static string VersionReleased {
            get {
                return ResourceManager.GetString("VersionReleased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version successfully update.
        /// </summary>
        public static string VersionUpdated {
            get {
                return ResourceManager.GetString("VersionUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot add or update versions that have been released or deleted.
        /// </summary>
        public static string VersionUpdateForbidden {
            get {
                return ResourceManager.GetString("VersionUpdateForbidden", resourceCulture);
            }
        }
    }
}
