//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChangeBlog.Api.Localization.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ChangeBlogStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ChangeBlogStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChangeBlog.Api.Localization.Resources.ChangeBlogStrings", typeof(ChangeBlogStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested Changelog line has been deleted.
        /// </summary>
        public static string ChangeLogLineDeleted {
            get {
                return ResourceManager.GetString("ChangeLogLineDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while inserting or updating Changelog lines. Please try again later.
        /// </summary>
        public static string ChangeLogLineErrorOnInsertOrUpdate {
            get {
                return ResourceManager.GetString("ChangeLogLineErrorOnInsertOrUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lines with same text are not allowed. Duplicate: &apos;{0}&apos;.
        /// </summary>
        public static string ChangeLogLineSameText {
            get {
                return ResourceManager.GetString("ChangeLogLineSameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid format &apos;{0}&apos;.
        /// </summary>
        public static string InvalidFormat {
            get {
                return ResourceManager.GetString("InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid version id.
        /// </summary>
        public static string InvalidVersionId {
            get {
                return ResourceManager.GetString("InvalidVersionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid versioning scheme id.
        /// </summary>
        public static string InvalidVersioningSchemeId {
            get {
                return ResourceManager.GetString("InvalidVersioningSchemeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing request data.
        /// </summary>
        public static string MissingRequestData {
            get {
                return ResourceManager.GetString("MissingRequestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permission to perform this operation.
        /// </summary>
        public static string NoPermissionToPerformThisOperation {
            get {
                return ResourceManager.GetString("NoPermissionToPerformThisOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The related product has been closed.
        /// </summary>
        public static string ProductHasBeenClosed {
            get {
                return ResourceManager.GetString("ProductHasBeenClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product does not contain any versions.
        /// </summary>
        public static string ProductWithoutVersions {
            get {
                return ResourceManager.GetString("ProductWithoutVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource not found.
        /// </summary>
        public static string ResourceNotFound {
            get {
                return ResourceManager.GetString("ResourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Error.
        /// </summary>
        public static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Profile successfully updated.
        /// </summary>
        public static string UserProfileUpdated {
            get {
                return ResourceManager.GetString("UserProfileUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The related version has already been released.
        /// </summary>
        public static string VersionAlreadyReleased {
            get {
                return ResourceManager.GetString("VersionAlreadyReleased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The related version has been deleted.
        /// </summary>
        public static string VersionDeleted {
            get {
                return ResourceManager.GetString("VersionDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version not found.
        /// </summary>
        public static string VersionNotFound {
            get {
                return ResourceManager.GetString("VersionNotFound", resourceCulture);
            }
        }
    }
}
